SITE_SHOP_DISABLE_SPAWNERS: §cСмена существа в рассаднике монстров отключена!
SITE_SHOP_ITEMS_GUI_NAME: Доступные предметы
SITE_SHOP_ITEMS_NAME: Предметы
SITE_SHOP_ITEM_ALERT: §6Магазин §8| §fВсе предметы успешно выданы!
SITE_SHOP_ITEM_EMPTY_LORE:
- §7У вас нет доступных предметов
- §7Покупка на сайте §dlast-craft.com
SITE_SHOP_ITEM_EMPTY_NAME: §cНет доступных предметов
SITE_SHOP_ITEM_LORE_1:
- '§7Получить следующие предметы:'
SITE_SHOP_ITEM_LORE_2:
- ' '
- §cВНИМАНИЕ! У вас должно быть %s
- §cсвободных слотов в вашем инвентаре!
- ' '
SITE_SHOP_ITEM_LORE_3: §e▸ Нажмите, чтобы получить
SITE_SHOP_ITEM_LORE_4:
- '§7Цена: §e%s §7золота'
- ''
- §e▸ Нажмите, чтобы купить
SITE_SHOP_WAIT_MESSAGE: §6Магазин §8| §fУ вас есть §a%s §fпредметов, которые вы не
  забрали после покупки! Чтобы их забрать, напишите §7/give
